AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kansousen

Globals:
  Function:
    Timeout: 5

Parameters:
  Stage:
    Type: String
  ApiDomainName:
    Type: String
  Certificate:
    Type: String
  CognitoUserPool:
    Type: String
  CognitoUserPoolClient:
    Type: String

Resources:
  KansousenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: kifuId
          AttributeType: S
        - AttributeName: var
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdTs
          AttributeType: N
        - AttributeName: startTs
          AttributeType: N
        - AttributeName: sfen
          AttributeType: S
        - AttributeName: pos
          AttributeType: S
      KeySchema:
        - AttributeName: kifuId
          KeyType: HASH
        - AttributeName: var
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: Created
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Start
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: startTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Sfen
          KeySchema:
            - AttributeName: sfen
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: Position
          KeySchema:
            - AttributeName: pos
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
              - seq

  KansousenTablePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt KansousenTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt KansousenTable.Arn }

  KifuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/kifu
      Handler: kifu
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          KIFU_TABLE: !Ref KansousenTable

  KifuApiV2:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowMethods:
          - POST
          - GET
          - OPTIONS
        AllowOrigins:
          - '*'
      Domain:
        DomainName: !Ref ApiDomainName
        BasePath: /v1
        CertificateArn: !Ref Certificate
        SecurityPolicy: TLS_1_2
        EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          OAuth2Authorizer:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration:
              audience:
                - !Ref CognitoUserPoolClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
        DefaultAuthorizer: OAuth2Authorizer

  KifuApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/kifu
      Handler: kifu
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt KifuFunction.Arn
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          KIFU_FUNCTION: !GetAtt KifuFunction.Arn
          BASE_PATH: !Sub "/${Stage}"
      Events:
        KifuApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref KifuApiV2

  HealthApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/ok
      Handler: ok
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KansousenTable
          BASE_PATH: !Sub "/${Stage}"
      Events:
        HealthApiEvent:
          Type: HttpApi
          Properties:
            Path: /ok
            Method: GET
            ApiId: !Ref KifuApiV2
            Auth:
              Authorizer: NONE

  KifuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: kifuId
          AttributeType: S
        - AttributeName: var
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdTs
          AttributeType: N
        - AttributeName: startTs
          AttributeType: N
        - AttributeName: sfen
          AttributeType: S
        - AttributeName: seq
          AttributeType: N
        - AttributeName: pos
          AttributeType: S
      KeySchema:
        - AttributeName: kifuId
          KeyType: HASH
        - AttributeName: var
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: Created
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdTs
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Start
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: startTs
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Sfen
          KeySchema:
            - AttributeName: sfen
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: Position
          KeySchema:
            - AttributeName: pos
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: Step
          KeySchema:
            - AttributeName: kifuId
              KeyType: HASH
            - AttributeName: seq
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: kansousen-api
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Ref CognitoUserPool
        AwsRegion: !Ref AWS::Region
        DefaultAction: DENY

  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: graphql/schema.graphql

  KifuTablePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt KifuTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt KifuTable.Arn }

  KifuDataSourceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: appsync/kifu/
      Handler: kifu
      Runtime: go1.x
      Policies:
        - !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KifuTable

  GraphQLPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:InvokeAsync
            Resource:
              - !GetAtt KifuDataSourceFunction.Arn

  GraphQLServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - !Ref GraphQLPolicy

  GraphQLDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      Name: KifuDataSource
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt GraphQLServiceRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !GetAtt KifuDataSourceFunction.Arn

  KifuResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DataSourceName: !GetAtt GraphQLDataSource.Name
      TypeName: Query
      FieldName: kifu
      RequestMappingTemplateS3Location: graphql/request.json

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
  StackName:
    Description: "StackName"
    Value: !Ref AWS::StackName
  KifuTable:
    Description: "Table name for Kifu"
    Value: !Ref KansousenTable
  ApiRegionalDomainName:
    Description: "Set CNAME record"
    Value: !GetAtt KifuApiV2.DomainName.RegionalDomainName
