AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kansousen

Globals:
  Function:
    Timeout: 5

Parameters:
  Stage:
    Type: String
    Default: prod
  ApiDomainName:
    Type: String
  SiteDomainName:
    Type: String
  AuthDomainName:
    Type: String
  Certificate:
    Type: String
  CognitoUserPool:
    Type: String
  CognitoUserPoolClient:
    Type: String

Resources:
  KansousenTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: kifuId
          AttributeType: S
        - AttributeName: var
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: createdTs
          AttributeType: N
        - AttributeName: startTs
          AttributeType: N
        - AttributeName: sfen
          AttributeType: S
        - AttributeName: pos
          AttributeType: S
      KeySchema:
        - AttributeName: kifuId
          KeyType: HASH
        - AttributeName: var
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: Created
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: createdTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Start
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: startTs
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - kifu
              - version
        - IndexName: Sfen
          KeySchema:
            - AttributeName: sfen
              KeyType: HASH
            - AttributeName: userId
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY
        - IndexName: Position
          KeySchema:
            - AttributeName: pos
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - userId
              - seq

  KansousenTablePolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:GetItem
              - dynamodb:BatchGetItem
              - dynamodb:Query
              - dynamodb:DescribeTable
              - dynamodb:PutItem
              - dynamodb:BatchWriteItem
              - dynamodb:DeleteItem
            Resource:
              - !GetAtt KansousenTable.Arn
              - !Sub
                - "${TableARN}/index/*"
                - { TableARN: !GetAtt KansousenTable.Arn }

  KifuFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/kifu
      Handler: kifu
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KansousenTable

  KifuApiV2:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref Stage
      CorsConfiguration:
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowMethods: "'POST'"
        AllowOrigins: "'*'"
      Domain:
        DomainName: !Ref ApiDomainName
        CertificateArn: !Ref Certificate
        SecurityPolicy: TLS_1_2
        EndpointConfiguration: REGIONAL
      Auth:
        Authorizers:
          OAuth2Authorizer:
            IdentitySource: '$request.header.Authorization'
            JwtConfiguration:
              audience: !Ref CognitoUserPoolClient
              issuer: !Sub "https://cognito-idp.${AWS::Region}.amazonaws.com/${CognitoUserPool}"
        DefaultAuthorizer: OAuth2Authorizer

  KifuApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/kifu
      Handler: kifu
      Runtime: go1.x
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt KifuFunction.Arn
      Environment:
        Variables:
          CONFIG_URL: !Sub "https://${SiteDomainName}/config.json"
      Events:
        KifuApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/{proxy+}
            Method: POST
            ApiId: !Ref KifuApiV2

  HealthApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/ok
      Handler: ok
      Runtime: go1.x
      Policies: !Ref KansousenTablePolicy
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          TABLE_NAME: !Ref KansousenTable
      Events:
        HealthApiEvent:
          Type: HttpApi
          Properties:
            Path: /v1/ok
            Method: GET
            ApiId: !Ref KifuApiV2
            Auth:
              Authorizer: NONE

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
  StackName:
    Description: "StackName"
    Value: !Ref AWS::StackName
  KifuTable:
    Description: "Table name for Kifu"
    Value: !Ref KansousenTable
  KifuFunction:
    Description: "KifuFunction Arn"
    Value: !GetAtt KifuFunction.Arn
