AWSTemplateFormatVersion: '2010-09-09'
Description: >
  kansousen auth

Parameters:
  Stage:
    Type: String
  SiteDomainName:
    Type: String
  AuthDomainName:
    Type: String
  CognitoCertificate:
    Type: String

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UsernameAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: False
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: False
          RequireNumbers: False
          RequireSymbols: False
          RequireUppercase: False
          TemporaryPasswordValidityDays: 7
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: False
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Priority: 1
            Name: verified_email
      AutoVerifiedAttributes:
        - email
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      SupportedIdentityProviders:
        - COGNITO
      GenerateSecret: false
      CallbackURLs:
        - !Sub "https://${SiteDomainName}/callback"
        - http://localhost:8080/callback
      LogoutURLs:
        - !Sub "https://${SiteDomainName}/"
        - http://localhost:8080/
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
        - aws.cognito.signin.user.admin
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      TokenValidityUnits:
        IdToken: "hours"
        AccessToken: "hours"
        RefreshToken: "days"
      IdTokenValidity: 1
      AccessTokenValidity: 1
      RefreshTokenValidity: 30

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref CognitoUserPool
      Domain: !Ref AuthDomainName
      CustomDomainConfig:
        CertificateArn: !Ref CognitoCertificate

  CognitoUserPoolId:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/kansousen/${Stage}/userPoolId"
      Value: !Ref CognitoUserPool

  CognitoUserPoolClientId:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub "/kansousen/${Stage}/userPoolClientId"
      Value: !Ref CognitoUserPoolClient

Outputs:
  Region:
    Description: "Region"
    Value: !Ref AWS::Region
  StackName:
    Description: "StackName"
    Value: !Ref AWS::StackName
  UserPoolClientID:
    Description: "User Pool Client ID"
    Value: !Ref CognitoUserPoolClient
  UserPoolID:
    Description: "User Pool ID"
    Value: !Ref CognitoUserPool
