version: 0.2

env:
  parameter-store:
    API_DOMAIN_NAME: /kansousen/$STAGE/apiDomainName
    SITE_DOMAIN_NAME: /kansousen/$STAGE/siteDomainName
    AUTH_DOMAIN_NAME: /kansousen/$STAGE/authDomainName
    COGNITO_CERTIFICATE: /kansousen/$STAGE/cognitoCertificate

phases:
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - jq --null-input --monochrome-output --compact-output --arg stage $STAGE --arg site $SITE_DOMAIN_NAME --arg auth $AUTH_DOMAIN_NAME --arg cert $COGNITO_CERTIFICATE '[{ParameterKey:"Stage",ParameterValue:$stage},{ParameterKey:"SiteDomainName",ParameterValue:$site},{ParameterKey:"AuthDomainName",ParameterValue:$auth},{ParameterKey:"CognitoCertificate",ParameterValue:$cert}]' > params.json
      - aws cloudformation deploy --stack-name $STACK_NAME --template-file auth/template.yaml --parameter-overrides file://params.json --no-fail-on-empty-changeset
