name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: $AWS_ROLE_ARN
        aws-region: $AWS_REGION
      env:
        AWS_ROLE_ARN: ${{ secrets.ROLE_ARN }}
        AWS_REGION: ${{ secrets.REGION }}

    - name: Execute pipeline
      run: aws sts get-caller-identity
