name: Release

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:

  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2

#    - name: Set up Go
#      uses: actions/setup-go@v2
#      with:
#        go-version: 1.17
#
#    - name: Test
#      run: go test -v ./...

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.ROLE_ARN }}
        aws-region: ${{ secrets.REGION }}

    - name: Execute pipeline
      run: aws sts get-caller-identity
